name: Deploy App
on:
  workflow_run:
    workflows: ["Publish Library"]
    types: [completed]
  push:
    branches: [master]
    paths: ['app/**']

jobs:
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install app dependencies
        working-directory: app
        run: npm ci
      
      - name: Wait for npm publish to propagate (1min)
        run: sleep 60

      - name: Install latest library
        working-directory: app
        run: npm install @moondreamsdev/dreamer-ui@latest

      - name: Build app
        working-directory: app
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DREAMERUI }}
          channelId: live
          projectId: dreamerui
          entryPoint: app
