name: Hosting Preview on Pull Request
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install lib deps
        working-directory: lib
        run: npm ci

      - name: Build lib
        working-directory: lib
        run: npm run build

      - name: Install local lib
        working-directory: app
        run: npm install ../lib

      - name: Install remaining app deps
        working-directory: app
        run: npm ci --ignore-scripts

      - name: Build app
        working-directory: app
        run: npm run build:local
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DREAMERUI }}
          projectId: dreamerui
          entryPoint: app
